apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: "2048-game"
  labels:
    app: servicelabel
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: "2048"
